apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: agilesolutions/skaffold-example
# not on windows read https://skaffold.dev/docs/how-tos/testers/
#test:
#  - image: agilesolutions/skaffold-example
#    structureTests:
#      - './structure-test/*'
deploy:
  kubectl:
    manifests:
      - k8s-*
#  helm:
#    releases:
#      - name: skaffold-example
#        chartPath: charts/skaffold-example
#        values:
#          image: skaffold-example