apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: agilesolutions/skaffold-example
test:
  - image: agilesolutions/skaffold-example
    structureTests:
      - ./image-tests/*
deploy:
#  kubectl:
#    manifests:
#      - k8s-*
  helm:
    releases:
      - name: skaffold-example
        chartPath: charts/skaffold-example
        values:
          image: skaffold-example