apiVersion: v1
description: Sample app agilesolution skaffold app
icon: https://www.gravatar.com/userimage/76010/21eb5b476821450e977b10d195212c1b?size=60
name: skaffold-example
version: 0.1.0-SNAPSHOT